### ISSUE TITLE
Change motor driver away from GPIO15

### ISSUE THREAD

**Issue by stkdiretto** [radforschung/lock#2]
GPIO 15 is used by TTGO's T-Beam for interfacing with the GPS module. To make the codebase interoperable with the T-Beam (e.g., if one chooses to use this module for testbed purposes), `PIN_LOCK_MOTOR` should be mapped to another pin

**Comment by robbi5** [comment]
TTGO T-Beam uses GPIO 12 (RX) & 15 (TX):
https://github.com/LilyGO/TTGO-T-Beam/blob/b447a35961dade031279dd4a29d01737cd9251be/GPS/GPS.ino#L13
